fix nrwmap rename

diff --git a/.github/workflows/test_e2e_portal.yml b/.github/workflows/test_e2e_portal.yml
--- a/.github/workflows/test_e2e_portal.yml
+++ b/.github/workflows/test_e2e_portal.yml
@@ -122,8 +122,8 @@ jobs:
 
       - name: Verify frontend submodule checkout
         run: |
-          test -f ${{ env.frontendPath }}/src/go-web-app/app/src/components/NrwMap/index.tsx \
-            || (echo "go-web-app submodule sparse-checkout is missing NrwMap; aborting." && exit 1)
+          test -f ${{ env.frontendPath }}/src/go-web-app/app/src/components/Nrw/index.tsx \
+            || (echo "go-web-app submodule sparse-checkout is missing Nrw; aborting." && exit 1)
 
       - name: Run the frontend
         run: |
